name: Send PRs that require review to Slack
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [review_requested]

permissions: {}

jobs:
  send-pr-to-slack-for-review:
    runs-on: ubuntu-20.04
    if: >-
      contains(github.event.comment.body, '@woocommerce/solaris') || 
      github.event.pull_request.requested_teams[*].slug == 'woocommerce/solaris'
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github/actions/pr-scrub-notify-slack
          ref: trunk
      - name: Notify Slack
        uses: archive/github-actions-slack@d9dae40827adf93bddf939db6552d1e392259d7d
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ inputs.TEST_ASSISTANCE_BOT_TOKEN }}
          slack-channel: ${{ inputs.WOO_PR_TESTING_REVIEW_SLACK_CHANNEL }}
          slack-text: |
              <!subteam^${{ inputs.WOO_PR_TESTING_REVIEW_TEAM_ID }}>There is a new PR waiting for review:
              <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}> :thread:
          slack-optional-unfurl_links: false
          slack-optional-unfurl_media: false
