name: Send PRs that require review to Slack

on:
  pull_request:
    types: [review_requested]
  issue_comment:
    types: [created]

permissions: {}

jobs:
  set-woo-pr-testing-review-team:
    runs-on: ubuntu-20.04
    outputs:
      team: ${{ steps.set-team.outputs.team }}
    steps:
      - name: Set WOO_PR_TESTING_REVIEW_TEAM
        id: set-team
        run: echo "::set-output name=team::${{ secrets.WOO_PR_TESTING_REVIEW_TEAM }}"
        
  send-pr-to-slack-for-review:
    runs-on: ubuntu-20.04
    needs: [set-woo-pr-testing-review-team]
    env: 
      WOO_PR_TESTING_REVIEW_TEAM: ${{ needs.set-woo-pr-testing-review-team.outputs.team }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Notify Slack
        uses: archive/github-actions-slack@d9dae40827adf93bddf939db6552d1e392259d7d
        id: notify
        if: |
          github.event_name == 'pull_request' &&
          github.event.action == 'review_requested' &&
          contains(join(github.event.pull_request.requested_teams.*.slug, ' '), ${{ env.WOO_PR_TESTING_REVIEW_TEAM }})
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.TEST_ASSISTANCE_BOT_TOKEN }}
          slack-channel: ${{ secrets.WOO_PR_TESTING_REVIEW_SLACK_CHANNEL }}
          slack-text: |
              <!subteam^${{ secrets.WOO_PR_TESTING_REVIEW_TEAM_ID }}>There is a new PR waiting for review:
              <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}> :thread:
          slack-optional-unfurl_links: false
          slack-optional-unfurl_media: false

  notify-comment-to-slack:
    runs-on: ubuntu-20.04
    needs: [set-woo-pr-testing-review-team]
    env: 
      WOO_PR_TESTING_REVIEW_TEAM: ${{ needs.set-woo-pr-testing-review-team.outputs.team }}
    steps:
      - name: Notify Slack
        uses: archive/github-actions-slack@d9dae40827adf93bddf939db6552d1e392259d7d
        id: notify
        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, ${{ env.WOO_PR_TESTING_REVIEW_TEAM }})
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.TEST_ASSISTANCE_BOT_TOKEN }}
          slack-channel: ${{ secrets.WOO_PR_TESTING_REVIEW_SLACK_CHANNEL }}
          slack-text: |
              <!subteam^${{ secrets.WOO_PR_TESTING_REVIEW_TEAM_ID }}> was mentioned in a comment:
              <${{ github.event.comment.html_url }}|View comment> :speech_balloon:
          slack-optional-unfurl_links: false
          slack-optional-unfurl_media: false
